---
title: "RWorksheet_Olivo#3"
output: pdf_document
date: "2023-10-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r name, echo = TRUE}

LETTERS
# 1
# LETTERS vector
# a.
first11 <- LETTERS[c(1:11)]
first11

# b.
lenLet <- length(LETTERS)
oddNum <- LETTERS[seq(lenLet) %% 2 == 1]
oddNum

# c
vowels <- LETTERS[c(1,5,9,15,21)]
vowels

#letters vector
# d
letters

last5 <- letters[c(22:26)]
last5

# e
fifto24 <- letters[c(15:24)]
fifto24

# 2
# a

city <- c("Tuguegarao City", "Manila", "Iloilo City", "Tacloban", "Samal Island", "Davao City")
city

# b
temp <- c(42, 39, 34, 34, 30, 27)
temp

# c
city_temp <- data.frame(city,temp)

View(city_temp)

# d
names(city_temp) <- c("City", "Temperature")
View(city_temp)

# e

str(city_temp)
# the code displayed the structure of the city_temp object
# it displayed the contents of the data frame
# it displayed the summary of the data frame

# f
twoRows <- city_temp[3:4,]

# g
highest <- city_temp[which.max(city_temp$Temperature),]
highest


lowest <- city_temp[which.min(city_temp$Temperature),]
lowest


# USING MATRICES

# 2 a

matr <- matrix(c(1:8,11:14), nrow = 3, ncol = 4)
matr

# b

mulMatr <- matr * 2
mulMatr

# c

rowTwooo <- mulMatr[2,]
rowTwooo

# d

twoColsAndRows <- mulMatr[c(1,2),c(3,4)]
twoColsAndRows

# e 

twoColsOneRow <- mulMatr[3,c(2,3)]
twoColsOneRow

# f

fourCol <- mulMatr[,4]
fourCol

# g 
dimnames(mulMatr) <- list(c("isa", "dalawa", "tatlo"), c("uno", "dos", "tres", "quatro"))

mulMatr

# h

matr
dim(matr) <- c(6,2)
matr


# ARRAYS

# 3 a 

```